### ISSUE TITLE
[REVIEW] Open Materials Review

### ISSUE THREAD

**Issue by codementum** [journalovi/2023-park-gatherplots#5] opened 2023-06-22 19:19 UTC
@nickelm 

Additional supplemental material is needed to meet JoVi transparency and open research requirements.

Empirical data from the experiment was included in the submission, but both data collection material and analysis code appear to be missing.
To fix: please either update the empirical data repository with data collection material and analysis code, or update the submission to include links to these repositories if kept separately.
Further guidelines can be found here: https://www.journalovi.org/author-guide.html#transparency-requirements

Some of the existing supplemental material needs to be put into longer term archival services.
The code for the technique is currently on GitHub, but needs to additionally be archived on a service like OSF or Zenodo. Instructions on making this change can be found here: https://www.journalovi.org/author-guide.html#non-compliant-repositories

**Comment by mjskay** [comment] 2024-02-07 22:27
Moving this discussion here since it may also requiring weighing in from the OC (cc @floe @chatchavan @lonnibesancon).

@nickelm thanks for the careful response and archaeological work here. Because of our commitment to research transparency, I think at a journal level we want to be sure we're setting the right standard. 

Maybe it would help our discussion if you could provide a list of what materials exist for the paper and what are missing? Then we could discuss specific cases more easily.

Thanks!

(original comment on #1 copied below)

-------------------

              > ensure all appropriate supplemental materials are included: e.g. experimental data, experimental analysis code, source code for artifacts, etc. For a full list of requirements see the transparency section of the author guide

This is well received. In response, I have collected further material from my coauthors and uploaded the available files and protocols to OSF (https://osf.io/bk9cx/). However, as noted by several reviewers, this is an older project that was completed some time ago; in fact, the study was run in 2014. Both students who participated in the project have moved on to faculty careers of their own. The students have all provided all available files, but it is not complete. I have uploaded what I was able to recover. I hope that this article's value supersedes its weaknesses in research transparency.

The analysis for the study data was recently updated in preparation for this submission and is available. I have uploaded it to the OSF as `bootstrap.html`. Note, however, that this is an interactive JavaScript application designed to be run with an active user. The Vega JSON files it generates for producing the SVG plots were already to be found in the `plots/` folder.

> check they are in appropriate long-term repositories (e.g. OSF, Zenodo, etc). Github repositories are okay as long as they are also archived on something like OSF or Zenodo. One easy way to archive + DOI an existing github repo is with Zenodo; see here

I have added the GitHub repository to the OSF (https://osf.io/bk9cx/). I will create a registration at the end of the major revision process (and after additional future revisions).

> check they are listed in the abstract and the required Materials section of the paper

The OSF is indeed listed in the abstract (under Materials).

> if any materials are missing, create an issue tagging the authors and ask them to add those materials

Please let me know if anything is still missing.

_Originally posted by @nickelm in https://github.com/journalovi/2023-park-gatherplots/issues/1#issuecomment-1913734783_

**Comment by nickelm** [comment] 2024-02-24 21:23
> Maybe it would help our discussion if you could provide a list of what materials exist for the paper and what are missing? Then we could discuss specific cases more easily.

Based on the major revision I just submitted, which included dropping some analysis based on reviewer feedback (the logistic regression and ANOVA analysis, in particular), I believe the situation stands as follows:

Available material (on https://osf.io/bk9cx/):
* Study performance data - gatherplots-FINAL.csv (CSV file)
* Data dictionary - README.md
* Interactive data analysis code - bootstrap.html
* Qualtrics survey - qualtrics.pdf (one specific run for one of the between-participant factors)
* Vega-Lite plot specs (in the paper GitHub)
* Quarto and Observable source code (registered on OSF)

Missing material:
* Participant compensation on Mechanical Turk
* Krusal-Wallis analysis code (for Confidence metric)
* Actual bootstrapping analysis script (because it was done interactively)

Material that is available but currently not added to the OSF
* IRB application
* Consent form (for Mechanical Turk)
* Recruitment material (for Mechanical Turk)
* Demographics survey (we never report on this in the paper)

Let me know if there is anything I can add to this or if I should add any of the available materials to the OSF.

**Comment by mjskay** [comment] 2024-02-24 23:09
Thanks @nickelm!

One question I had about the bootstrapping was were participants used to stratify the bootstrap? I tried looking at the data and using the bootstrap.html script to figure this out / recreate the charts, but I was having trouble getting it to work. So, I ended up just quickly recreating the analysis using linear mixed models (since that's more what I'm familiar with) to corroborate the results figures / overall pattern of results. FWIW, it comes out very similarly; see [here](https://mjskay.github.io/gatherplots-data/plot.html) (source [here](https://github.com/mjskay/gatherplots-data/blob/main/plot.qmd)).

**Comment by mjskay** [comment] 2024-03-21 15:57
Hi @nickelm --- thanks again for all the work getting the materials ready for this. We (the OC) had a conversation about this. 

Our guarantee as a journal is that data *and code* for an analysis is provided, but we don't currently make guarantees that the code works long term (i.e., we don't have a setup for checking the reproducibility of all submitted code). So, from that perspective, we think the code you provided for the bootstrapping analysis is sufficient.

However, we do think there should be some code for the Kruskal-Wallis analysis in order to satisfy the journal requirements. I've used the Kruskal-Wallis test before so I'd be happy to give pointers or help with that if needed.

Everything else you've listed looks good 👍.

Re: your list of _Material that is available but currently not added to the OSF_: if it's easy to add to the repo, we don't see any reason not to add it (maybe it helps some future person running a similar experiment...), **except** perhaps the IRB application. @lonnibesancon raised the point in our meeting that there may be some issues with sharing IRB application contents that you would need to check on before doing so; I'll let him comment further since I am not an expert in that area.

**Comment by nickelm** [comment] 2024-03-21 21:27
Thanks @mjskay. I will attend to this as soon as this pesky deadline is over. 😉 I look forward to @lonnibesancon's word on the IRB application.

**Comment by mjskay** [comment] 2024-03-21 21:30
Awesome, thanks! Good luck with the VIS deadline 😉.

**Comment by lonnibesancon** [comment] 2024-03-22 17:30
> Thanks @mjskay. I will attend to this as soon as this pesky deadline is over. 😉 I look forward to @lonnibesancon's word on the IRB application.

Hi @nickelm!
Regarding IRB approval documents there are two things I would consider. 

1. IRBs do not seem to always agree/approve that such documents are made available publicly. My understanding is that the rules will change in different countries and institutions so please check that you are allowed to share. I am in favor of sharing because...
2. ... there are benefits for meta-analysis and post-publication purposes. I am sure you are aware of our investigation into ethics approval from [last year](https://researchintegrityjournal.biomedcentral.com/articles/10.1186/s41073-023-00134-4). This analysis was difficult and the conclusions we could reach limited because the original ethics approval documents were not publicly available. So there is definitely value in sharing such documents, but keeping point 1 in mind before you do. 

Thanks for all of your efforts in making everything transparent and good luck with the upcoming deadline(s).

**Comment by nickelm** [comment] 2024-05-07 06:41
> Hi @nickelm! Regarding IRB approval documents there are two things I would consider.
> 
> 1. IRBs do not seem to always agree/approve that such documents are made available publicly. My understanding is that the rules will change in different countries and institutions so please check that you are allowed to share. I am in favor of sharing because...
> 2. ... there are benefits for meta-analysis and post-publication purposes. I am sure you are aware of our investigation into ethics approval from [last year](https://researchintegrityjournal.biomedcentral.com/articles/10.1186/s41073-023-00134-4). This analysis was difficult and the conclusions we could reach limited because the original ethics approval documents were not publicly available. So there is definitely value in sharing such documents, but keeping point 1 in mind before you do.
> 
> Thanks for all of your efforts in making everything transparent and good luck with the upcoming deadline(s).

Thanks for your guidance. In response, I've made the IRB documents available ([OSF](https://osf.io/bk9cx/))---I can't see this being a problem since these were all documents that we authored ourselves. Unfortunately, I don't have the approval documents from the IRB because I no longer have access to their internal IRB system (or my old email archives). 

@mjskay: I am still working on the Kruskal-Wallis analysis and will update here once this requirement has been satisfied and the code uploaded to OSF.

**Comment by nickelm** [comment] 2024-05-08 07:01
...and now the Kruskal-Wallis analysis of confidence has been uploaded to the OSF. As far as I can tell, this should be everything in terms of supplemental material.

**Comment by mjskay** [comment] 2024-05-08 13:51
Thanks @nickelm!

@codementum if that means all the open materials requirements are now fulfilled I believe we can close this.

**Comment by mjskay** [comment] 2024-05-27 03:28
I am updating this issue to contain the items from the new open materials checklist:

### Open Materials Checklist
- [x] Paper license is CC-BY
- [x] The "Research materials" section in the paper exists.
- [x] Links to supplements and materials are listed in at least the following locations:
   - [x] Abstract (according to the [structured abstract requirement](https://www.journalovi.org/author-guide.html#abstract))
   - [x] "Research materials" section of the paper.
- [x] All links to repositories and materials in the paper can be reached.
- [x] All materials are in repositories that meet the [FAIR principles](https://www.go-fair.org/fair-principles/) (e.g. OSF, Zenodo, etc). Non-long-term hosting solutions, such as Github or self-hosted websites, are acceptable only if they are also archived on a long term repository like OSF or Zenodo. One easy way to archive + DOI an existing Github repo is with Zenodo; see [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)
- [x] Check that all other requirements under the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements) are fulfilled.

I will check these off quickly (I think they are all done) and then notify if anything is missing.

**Comment by mjskay** [comment] 2024-05-27 03:46
This looks good, too. Closing.

**Closed as completed by mjskay** 2024-05-27 03:46 UTC
Labels: review
